### ISSUE TITLE
generic_indel contains Pindel specific fields.

### ISSUE THREAD

**Issue by zhouyangyu** [leukgen/click_annotvcf#2]
When running `click_annotvcf annotvcf --pipe generic_indel ...`, the program assumes there is a “LEN” field under INFO, but that’s not always the case for generic indel vcf (e.g. strelka vcf doesnt have LEN). We need another way to calculate END position without using LEN, maybe just based on the length of ALT?
https://github.com/leukgen/click_annotvcf/blob/b9d325665a99c900de818bace2652a4824dec6e6/click_annotvcf/annotvcf.py#L123

**Comment by juanesarango** [comment]
this issue was fixed with PR #4
