### ISSUE TITLE
no VAF for PASS variants

### ISSUE THREAD

**Issue by zhouyangyu** [leukgen/click_annotvcf#6]
There's no VAF reported in the output tsv for some PASS variants. For example, `2    25994361` is PASS but it does not have VAF in `/ifs/work/leukgen/home/zhouy1/repos/projects/p221/results/I-H-132599-T1-1-D1-1/snvs/I-H-132599-T1-1-D1-1_vs_I-H-100778-N1-1-D1-1.snvs.output.annot.bed.coding.tsv.gz`.

**Comment by juanesarango** [comment]
When metrics had falsy values I was setting all values to NA, and as Strelka did not give `dirprop` field, I was replacing Strelka VAF values with NA. 

This bug was fixed in commit e0b0fb17cda11c162543c5158de4d93a7fd5fdf0.
